version: '3.9'

services:
  db:
    image: postgres:15
    container_name: soderia_db
    restart: always
    environment:
      POSTGRES_DB: soderia
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: fattorbrondani
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: soderia_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata:
